### ISSUE TITLE
[ENH] Add testing data

### ISSUE THREAD

**Issue by mattcieslak** [nipreps/sdcflows#1]
We can use https://openneuro.org/datasets/ds001600/versions/1.0.0 to get a pepolar, phasediff and 3 different versions of phase1/phase2. I'm checking on whether we can add a 4th version of phase1/phase2 from a 7T magnet (which is of course different from the other 3)

- [ ] Create stand-alone archives containing one of each BIDS-compatible fieldmap type. 
- [ ] Upload somewhere public. UPenn Box or the osf server?
- [ ] add to circleci download job

**Comment by effigies** [comment]
I might be misunderstanding the checklist, but if what you need is access to the OpenNeuro data on CircleCI, you can just use datalad:

```
datalad install ///openneuro/ds001600
datalad get ds001600/sub-1/fmap
```

As an example, I do that for preprocessed data in FitLins tests: https://github.com/poldracklab/fitlins/blob/5b3b248d7a4ffb1d771d8de44473dd166ccba039/.circleci/config.yml#L61-L92

**Comment by mattcieslak** [comment]
That's very useful, I wasn't aware of the markiewicz/datalad:0.0.1 image.

I was thinking I would break these up into independent archives so that each is a valid BIDS dataset and has a single fieldmap in the fmaps directory. Otherwise the IntendedFor's will get messy

**Comment by effigies** [comment]
Oh, I see. We could probably still take advantage of datalad by pulling it down and creating git branches that remove all but one set of fieldmaps. It would need to be written so that it's idempotent when run on a pre-cached copy and no changes have been made upstream.

For reference, the image is just [this](https://github.com/effigies/datalad-docker/blob/master/Dockerfile). I created it because conda installs were taking more time than the data fetches.

**Comment by effigies** [comment]
Oh, looks like you can use [`git worktree`](https://riptutorial.com/git/example/13145/using-a-worktree) to checkout branches into separate directories. That should make things relatively easy to work with.
