### ISSUE TITLE
Improve PEPOLAR robustness

### ISSUE THREAD

**Issue by mgxd** [nipreps/sdcflows#192]
Currently, we are assuming all affines match across the EPI fieldmaps in pepolar correction.

A more robust solution would include adding the following steps:
- Estimate a reference image for each phase encoding direction (`StructuralReference`)
- Use one of these images as the reference, and the others as moving images to register.

**Comment by oesteban** [comment]
> Currently, we are assuming all affines match across the EPI fieldmaps in pepolar correction.

More worryinglyy, we are assuming that the EPI "blips" are in register. They may not be.

> * Estimate a reference image for each phase encoding direction (`StructuralReference`)
> 
> * Use one of these images as the reference, and the others as moving images to register.

These two steps would better be renamed as:
* Within-blip alignment (`StructuralReference`) - when we have several 3D or 4D files, assumes `PhaseEncodingDirection` and `TotalReadoutTime` are the same for all of them.
* Between-blip alignment (using `antsRegistration`) - one of the averages calculated in the within-blip step is taken for reference (e.g., the highest resolution of all) and the other averages are registered to that reference.

**Comment by oesteban** [comment]
I completely switched my way of thinking during the development of #197:

> More worryingly, we are assuming that the EPI "blips" are in register. They may not be.

Although this is true, TOPUP has the possibility of registering the "blips". I believe its configuration is probably better than any approach we can come up with for the problem at hand. As an exception, the "_quick" configuration of TOPUP in our settings does not have estimation of realignment parameters - in that case, #197 very simply sets up 3dVolReg for a fast alignment.

> Within-blip alignment

Using StructuralReference for this can be problematic with varying total readout times, because in that case they should be considered different blips. In practice, for this one it is better to just use TOPUP.

> Between-blip alignment

I feel we are over-complicating here. This facet of the problem would be resolve straightforwardly with a reference workflow to feed the pepolar estimation. So let's push this one away until we better integrate the reference workflow. That said, TOPUP should deal with this case fairly well too.
