### ISSUE TITLE
Support for orthogonal configurations in PEPOLAR with TOPUP

### ISSUE THREAD

**Issue by mgxd** [nipreps/sdcflows#193]
I believe we currently only handle AP/PA correction, but LR/RL is possible as well.

**Comment by oesteban** [comment]
We do handle the two pairs. What I think we don't support is using orthogonal (e.g., LR/PA) or orthogonal&colinear acquisitions (e.g., RL/LR/PA/AP).

**Comment by oesteban** [comment]
I changed the title:
- ~~Additional axis~~ -> it's orthogonal schemes what's missing.
- ~~correction~~ -> TOPUP is estimation (it can output "corrected" results, but the fundamental output is the estimated fieldmap, not the corrected EPIs)

**Comment by oesteban** [comment]
I'm going to close this one for the following reasons:
- Our circle CI tests include one dataset with AP/PA blips and one with LR/RL.
- I have looked into the code and I can't see where we are enforcing that the PE directions are colinear (or, another possibility, that all must have the same total readout time).
- There's currently no dataset in which we can test this.

If we found  a dataset to test this and turns out we are not supporting the use case, please reopen.
