### ISSUE TITLE
Too liberal mask of the magnitude image

### ISSUE THREAD

**Issue by oesteban** [nipreps/sdcflows#23]
@zenkavi this happened with your dataset:

![sub-200148_desc-brain_mask](https://user-images.githubusercontent.com/598470/61653326-e206fe80-ac6e-11e9-9787-b01e3c441b01.png)

Although it doesn't really seem to affect registration to the BOLD reference, we want to get this mask right 100% of the times.

**Comment by zenkavi** [comment]
@oesteban thanks for catching. Do you have the subject number? Should I re-run?

**Comment by oesteban** [comment]
> Do you have the subject number?

200148

> Should I re-run?

Nope, it seems to robustly replicate - and it doesn't seem to affect too badly in susceptibility correction. We can live with this.

**Comment by effigies** [comment]
See also [Neurostars #4789](https://neurostars.org/t/fmriprep-fieldmap-skull-stripping-problem/4789).

**Comment by rob-mccutcheon** [comment]
Hi, I have been having problems with the skullstripping of fieldmaps while using fmriprep as detailed in [ Neurostars #4789](https://neurostars.org/t/fmriprep-fieldmap-skull-stripping-problem/4789). 

It was kindly suggested by @effigies to try modifying the sdcflows code, which I imagine might involved changing the value set for 'frac' at line 64[here](https://github.com/poldracklab/sdcflows/blob/master/sdcflows/workflows/fmap.py)


If I were to do this I am unsure, however, as to how then subsequently integrate the change I would make into my fmriprep singularity image? Any advice much appreciated

**Comment by oesteban** [comment]
@AKSoo

**Comment by kimsin98** [comment]
Ah, so BET threshold is a recurring problem.

What would be the best solution though? Just raising the current value (0.6) is a simple option, but that might not be robust. Another simple solution is adding it as an optional parameter. I've checked what parameters various other pipelines used for magnitude brain extraction and seen values ranging from 0.3 to 0.7, so that solution might actually be valid.

A hard option is implementing a more complicated but robust protocol. Perhaps adapting niworkflows skullstrip workflow?

@robmcc10 Late but you can patch docker/singularity images by mounting directories/files into them, as seen in the [fMRIPrep docs](https://fmriprep.readthedocs.io/en/stable/contributors.html#patching-working-repositories).
