### ISSUE TITLE
Improve fieldmap visualisation in the reports

### ISSUE THREAD

**Issue by chrisgorgo** [nipreps/sdcflows#4]
- use cold and hot colormap
- show the mm displacement field with color bar and scale
- show outline of the brain for reference

**Comment by oesteban** [comment]
See https://github.com/poldracklab/sdcflows/pull/28#issuecomment-518749843 to see how it looks now:
  - [x] use cold and hot colormap
  - [ ] show the mm displacement field with color bar and scale
  - [x] show outline of the brain for reference

The displacement field is not shown because this plot shows field inhomogeneity in Hz. To know how that converts into a displacements field, one needs to know the EPI acquisition details (i.e., imaging parameters of the fMRI or dMRI dataset that the correction will apply to).
